spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_db
    username: postgres
    password: 9198
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
